# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
---
name: Numpy Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [3.7]
        TYPE: [python-pip]
        include:
          - TYPE: python-pip
            INSTALL: pip
            PKG_INSTALL: pip
          - TYPE: conda-pip
            INSTALL: conda
            PKG_INSTALL: pip
          - TYPE: conda-conda
            INSTALL: conda
            PKG_INSTALL: conda

    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      MARTIX_NAME: ${{ matrix.os }}-python${{ matrix.python-version }}-${{ matrix.TYPE }}

    steps:
      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
          echo "${MARTIX_NAME}"
      - name: Dump job context
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        if: matrix.INSTALL == 'pip'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup conda
        if: matrix.INSTALL != 'pip'
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pytest psutil hypothesis
          pip install -e .

      - name: Show environment
        run: |
          python -VV
          python -c "from pprint import pprint; import os; pprint(dict(os.environ))"
          pip freeze
          echo "$MATRIX_CONTEXT"

      - name: Run dll sniff tests
        run: |
          python packages/numpy/scan.py

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Upload scan results
          path: packages/numpy/scan.json
