# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Numpy Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [3.7]
        TYPE: [python-pip, conda-pip, conda-conda]
        include:
          - TYPE: python-pip
            INSTALL: pip
            PKG_INSTALL: pip
          - TYPE: conda-pip
            INSTALL: conda
            PKG_INSTALL: pip
          - TYPE: conda-conda
            INSTALL: conda
            PKG_INSTALL: conda

    steps:

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      if: matrix.INSTALL == 'pip'
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      if: matrix.INSTALL != 'pip'
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pytest psutil hypothesis
        pip install -e .

    - name: Show environment:
      run: |
        python -VV
        python -c "from pprint import pprint; import os; pprint(dict(os.environ))"
        pip freeze

    - name: Test with pytest
      run: |
        python packages/numpy/scan.py

    - uses: actions/upload-artifact@v2
      with:
        name: Upload scan results
        path: packages/numpy/scan.json
