---
name: Numpy Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.5]
        TYPE: [python-pip, conda-pip, conda-conda]
        include:
          - TYPE: python-pip
            INSTALLER: pip
            PKG_INSTALL: pip
            EXEC: ''
          - TYPE: conda-pip
            INSTALLER: conda
            PKG_INSTALL: pip
            EXEC: conda run -n env
          - TYPE: conda-conda
            INSTALLER: conda
            PKG_INSTALL: conda
            EXEC: conda run -n env

    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      MATRIX_NAME: ${{ matrix.os }}-python${{ matrix.python-version }}-${{ matrix.TYPE }}
      MATRIX_CONTEXT: ${{ toJson(matrix) }}

    steps:
      - name: Check name
        run: echo "$MATRIX_NAME"

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        if: matrix.INSTALLER == 'pip'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup conda
        if: matrix.INSTALLER != 'pip'
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          conda-channels: anaconda, conda-forge

      - name: Create conda env
        if: matrix.INSTALLER != 'pip'
        run: conda create -y -n env python={{ matrix.python-version }}

      - name: Init conda windows
        if: (matrix.INSTALLER != 'pip') && (matrix.os == 'windows-latest')
        run: |
          conda init cmd.exe
          conda init powershell

      - name: Init conda macos
        if: (matrix.INSTALLER != 'pip') && (matrix.os == 'macos-latest')
        run: |
          conda init powershell

      - name: Install dependencies
        run: |
          ${{ matrix.EXEC }} python -m pip install --upgrade pip
          ${{ matrix.EXEC }} ${{ matrix.INSTALLER }} install pytest psutil hypothesis
          ${{ matrix.EXEC }} ${{ matrix.PKG_INSTALL }} install numpy
          ${{ matrix.EXEC }} pip install -e .

      - name: Show environment
        run: |

          ${{ matrix.EXEC }} python -VV
          ${{ matrix.EXEC }} python -c "from pprint import pprint; import os; pprint(dict(os.environ))"
          ${{ matrix.EXEC }} pip freeze

      - name: Run dll sniff tests
        run: |
          ${{ matrix.EXEC }} ${{ matrix.PKG_INSTALL }} -V
          ${{ matrix.EXEC }} python packages/numpy/scan.py

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.MATRIX_NAME }}
          path: packages/numpy/*.json
